### ISSUE TITLE
Group accounts

### ISSUE THREAD

**Issue by kieranroneill** [kibis-is/web-extension#333]
## Summary

Grouping accounts seems like a no-brainer type feature for AVM wallets as accounts are intrinsically linked. For example, an account can be re-keyed and keeping the this and the auth account in the same group is a definite use case.

## Acceptance Criteria

| Scenario 1 | User creates a group for an account                                  |
|----------------|-----------------------------------------------------------------------------|
| _GIVEN_   | no groups exist |
| _WHEN_   | the User presses "Add To Group" |
| _AND_      | the User enters the group name |
| _THEN_    | the account is added to the group |

| Scenario 2 | User creates a group for an account                                  |
|----------------|-----------------------------------------------------------------------------|
| _GIVEN_   | a group of accounts exist |
| _WHEN_   | the User presses "Add To Group" |
| _AND_      | the User selects the group from the list |
| _THEN_    | the account is added to the group |

| Scenario 3 | User removes the account from the group                         |
|----------------|-----------------------------------------------------------------------------|
| _GIVEN_   | an account is part of a group |
| _WHEN_   | the User presses "Remove From Group" |
| _THEN_    | the account is removed from the group |

**Comment by lancoer** [comment]
Good morning @kieranroneill 
Is deadline remains 6 days for this?

**Comment by kieranroneill** [comment]
Sorry, this deadline had to be bumped up until this week. I have been swamped with Kibisis mobile and some alpha Kibisis NFT work :sweat_smile: 

I will hopefully finish this today and release version 2.4.0 tomorrow :smile:
